<?php

namespace Webkul\Marketplace\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExtensionSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @param  array  $parameters
     * @return void
     */
    public function run($parameters = [])
    {
        DB::table('extension_reviews')->delete();
        DB::table('extension_versions')->delete();
        DB::table('extensions')->delete();

        $now = Carbon::now();
        $defaultLocale = $parameters['locale'] ?? config('app.locale');

        // Create sample extensions
        $extensions = [
            // Integrations
            [
                'id'               => 1,
                'name'             => 'Stripe Payment Gateway',
                'slug'             => 'stripe-payment-gateway',
                'description'      => 'Accept credit card payments directly in your CRM with Stripe integration',
                'long_description' => 'Seamlessly integrate Stripe payment processing into your Laravel CRM. Accept credit cards, manage subscriptions, handle refunds, and track all transactions from one central location. Features automatic payment reconciliation, webhook support for real-time updates, and comprehensive reporting.',
                'type'             => 'integration',
                'category_id'      => 12, // integrations-payment
                'price'            => 99.00,
                'status'           => 'approved',
                'downloads_count'  => 1547,
                'average_rating'   => 4.8,
                'featured'         => true,
                'logo'             => 'stripe-logo.png',
                'screenshots'      => json_encode(['stripe-1.png', 'stripe-2.png', 'stripe-3.png']),
                'documentation_url' => 'https://docs.example.com/stripe',
                'demo_url'         => 'https://demo.example.com/stripe',
                'repository_url'   => 'https://github.com/example/stripe-extension',
                'support_email'    => 'support@stripeextension.com',
                'tags'             => json_encode(['payment', 'stripe', 'e-commerce', 'billing']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(6),
                'updated_at'       => $now->copy()->subDays(5),
            ],
            [
                'id'               => 2,
                'name'             => 'Mailchimp Integration',
                'slug'             => 'mailchimp-integration',
                'description'      => 'Sync your contacts with Mailchimp and automate email marketing campaigns',
                'long_description' => 'Connect your CRM contacts with Mailchimp for powerful email marketing automation. Automatically sync contact information, segment audiences based on CRM data, track campaign performance, and trigger automated campaigns based on customer actions. Includes two-way sync, custom field mapping, and detailed analytics.',
                'type'             => 'integration',
                'category_id'      => 11, // integrations-email
                'price'            => 0.00,
                'status'           => 'approved',
                'downloads_count'  => 3284,
                'average_rating'   => 4.6,
                'featured'         => true,
                'logo'             => 'mailchimp-logo.png',
                'screenshots'      => json_encode(['mailchimp-1.png', 'mailchimp-2.png']),
                'documentation_url' => 'https://docs.example.com/mailchimp',
                'demo_url'         => null,
                'repository_url'   => null,
                'support_email'    => 'support@mailchimpextension.com',
                'tags'             => json_encode(['email', 'marketing', 'automation', 'mailchimp']),
                'requirements'     => json_encode(['PHP' => '>=8.0', 'Laravel' => '>=9.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(12),
                'updated_at'       => $now->copy()->subDays(15),
            ],
            [
                'id'               => 3,
                'name'             => 'Google Calendar Sync',
                'slug'             => 'google-calendar-sync',
                'description'      => 'Synchronize CRM activities and tasks with Google Calendar',
                'long_description' => 'Keep your team organized with seamless Google Calendar integration. Automatically sync meetings, tasks, and deadlines from your CRM to Google Calendar. Features real-time two-way sync, calendar event reminders, conflict detection, and support for multiple calendars. Perfect for sales teams who rely on Google Workspace.',
                'type'             => 'integration',
                'category_id'      => 14, // integrations-calendar
                'price'            => 49.00,
                'status'           => 'approved',
                'downloads_count'  => 2156,
                'average_rating'   => 4.5,
                'featured'         => false,
                'logo'             => 'google-calendar-logo.png',
                'screenshots'      => json_encode(['gcal-1.png', 'gcal-2.png', 'gcal-3.png', 'gcal-4.png']),
                'documentation_url' => 'https://docs.example.com/google-calendar',
                'demo_url'         => 'https://demo.example.com/calendar',
                'repository_url'   => null,
                'support_email'    => 'support@gcalextension.com',
                'tags'             => json_encode(['calendar', 'google', 'sync', 'scheduling']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(9),
                'updated_at'       => $now->copy()->subDays(20),
            ],
            [
                'id'               => 4,
                'name'             => 'Slack Notifications',
                'slug'             => 'slack-notifications',
                'description'      => 'Send real-time CRM notifications to Slack channels',
                'long_description' => 'Stay informed with instant Slack notifications for important CRM events. Get notified about new leads, deal updates, task assignments, and more. Customize notification rules, choose specific channels, and format messages to match your team\'s workflow. Includes slash commands for quick CRM actions from Slack.',
                'type'             => 'integration',
                'category_id'      => 15, // communication-chat
                'price'            => 0.00,
                'status'           => 'approved',
                'downloads_count'  => 4521,
                'average_rating'   => 4.9,
                'featured'         => true,
                'logo'             => 'slack-logo.png',
                'screenshots'      => json_encode(['slack-1.png', 'slack-2.png']),
                'documentation_url' => 'https://docs.example.com/slack',
                'demo_url'         => null,
                'repository_url'   => 'https://github.com/example/slack-extension',
                'support_email'    => 'support@slackextension.com',
                'tags'             => json_encode(['slack', 'notifications', 'chat', 'collaboration']),
                'requirements'     => json_encode(['PHP' => '>=8.0', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(8),
                'updated_at'       => $now->copy()->subDays(3),
            ],

            // Themes
            [
                'id'               => 5,
                'name'             => 'Modern Dashboard Theme',
                'slug'             => 'modern-dashboard-theme',
                'description'      => 'A sleek, modern theme with enhanced UI/UX and dark mode support',
                'long_description' => 'Transform your CRM with a beautiful, modern interface. Features a clean design, smooth animations, customizable color schemes, and full dark mode support. Optimized for productivity with improved navigation, better data visualization, and responsive layout that works perfectly on all devices. Includes 5 pre-built color schemes and extensive customization options.',
                'type'             => 'theme',
                'category_id'      => 2, // themes
                'price'            => 149.00,
                'status'           => 'approved',
                'downloads_count'  => 892,
                'average_rating'   => 4.7,
                'featured'         => true,
                'logo'             => 'modern-theme-logo.png',
                'screenshots'      => json_encode(['modern-1.png', 'modern-2.png', 'modern-3.png', 'modern-4.png', 'modern-5.png']),
                'documentation_url' => 'https://docs.example.com/modern-theme',
                'demo_url'         => 'https://demo.example.com/modern-theme',
                'repository_url'   => null,
                'support_email'    => 'support@moderntheme.com',
                'tags'             => json_encode(['theme', 'ui', 'dark-mode', 'modern']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(4),
                'updated_at'       => $now->copy()->subDays(10),
            ],
            [
                'id'               => 6,
                'name'             => 'Classic Enterprise Theme',
                'slug'             => 'classic-enterprise-theme',
                'description'      => 'Professional enterprise-grade theme with enhanced security features',
                'long_description' => 'A professional theme designed for enterprise environments. Features a clean, corporate design with enhanced security indicators, audit trail visualization, and compliance-focused UI elements. Includes customizable branding options, white-label support, and advanced permission indicators. Perfect for organizations with strict security and compliance requirements.',
                'type'             => 'theme',
                'category_id'      => 2, // themes
                'price'            => 199.00,
                'status'           => 'approved',
                'downloads_count'  => 456,
                'average_rating'   => 4.4,
                'featured'         => false,
                'logo'             => 'enterprise-theme-logo.png',
                'screenshots'      => json_encode(['enterprise-1.png', 'enterprise-2.png', 'enterprise-3.png']),
                'documentation_url' => 'https://docs.example.com/enterprise-theme',
                'demo_url'         => 'https://demo.example.com/enterprise-theme',
                'repository_url'   => null,
                'support_email'    => 'support@enterprisetheme.com',
                'tags'             => json_encode(['theme', 'enterprise', 'security', 'compliance']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(3),
                'updated_at'       => $now->copy()->subDays(7),
            ],

            // Productivity
            [
                'id'               => 7,
                'name'             => 'Advanced Reports & Analytics',
                'slug'             => 'advanced-reports-analytics',
                'description'      => 'Comprehensive reporting suite with customizable dashboards and analytics',
                'long_description' => 'Take your CRM analytics to the next level with advanced reporting capabilities. Create custom reports with drag-and-drop interface, build interactive dashboards, schedule automated report delivery, and export to multiple formats. Includes 50+ pre-built report templates, advanced filtering, data visualization options, and real-time metrics. Perfect for data-driven teams.',
                'type'             => 'plugin',
                'category_id'      => 4, // analytics
                'price'            => 199.00,
                'status'           => 'approved',
                'downloads_count'  => 1234,
                'average_rating'   => 4.8,
                'featured'         => true,
                'logo'             => 'reports-logo.png',
                'screenshots'      => json_encode(['reports-1.png', 'reports-2.png', 'reports-3.png', 'reports-4.png']),
                'documentation_url' => 'https://docs.example.com/reports',
                'demo_url'         => 'https://demo.example.com/reports',
                'repository_url'   => null,
                'support_email'    => 'support@reportsextension.com',
                'tags'             => json_encode(['analytics', 'reports', 'dashboard', 'insights']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(10),
                'updated_at'       => $now->copy()->subDays(2),
            ],
            [
                'id'               => 8,
                'name'             => 'Task Automation Engine',
                'slug'             => 'task-automation-engine',
                'description'      => 'Automate repetitive tasks and workflows with no-code automation builder',
                'long_description' => 'Save hours every week with powerful workflow automation. Create complex automation rules using a visual no-code builder. Trigger actions based on CRM events, schedule recurring tasks, assign work automatically, and integrate with external services. Includes templates for common workflows, conditional logic, and detailed execution logs.',
                'type'             => 'plugin',
                'category_id'      => 10, // automation
                'price'            => 129.00,
                'status'           => 'approved',
                'downloads_count'  => 2048,
                'average_rating'   => 4.6,
                'featured'         => true,
                'logo'             => 'automation-logo.png',
                'screenshots'      => json_encode(['automation-1.png', 'automation-2.png', 'automation-3.png']),
                'documentation_url' => 'https://docs.example.com/automation',
                'demo_url'         => 'https://demo.example.com/automation',
                'repository_url'   => null,
                'support_email'    => 'support@automationextension.com',
                'tags'             => json_encode(['automation', 'workflow', 'no-code', 'productivity']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(7),
                'updated_at'       => $now->copy()->subDays(12),
            ],
            [
                'id'               => 9,
                'name'             => 'Document Management Pro',
                'slug'             => 'document-management-pro',
                'description'      => 'Advanced document storage, versioning, and collaboration features',
                'long_description' => 'Manage all your customer documents in one place with advanced document management. Features include version control, document templates, e-signature integration, automated filing, OCR text extraction, and advanced search. Share documents securely with customers via branded portals. Supports all major file formats with preview capabilities.',
                'type'             => 'plugin',
                'category_id'      => 3, // productivity
                'price'            => 79.00,
                'status'           => 'approved',
                'downloads_count'  => 1689,
                'average_rating'   => 4.5,
                'featured'         => false,
                'logo'             => 'documents-logo.png',
                'screenshots'      => json_encode(['docs-1.png', 'docs-2.png', 'docs-3.png']),
                'documentation_url' => 'https://docs.example.com/documents',
                'demo_url'         => null,
                'repository_url'   => null,
                'support_email'    => 'support@documentsextension.com',
                'tags'             => json_encode(['documents', 'files', 'storage', 'versioning']),
                'requirements'     => json_encode(['PHP' => '>=8.0', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(5),
                'updated_at'       => $now->copy()->subDays(8),
            ],

            // Sales & Marketing
            [
                'id'               => 10,
                'name'             => 'Email Campaign Builder',
                'slug'             => 'email-campaign-builder',
                'description'      => 'Create and send beautiful email campaigns with drag-and-drop builder',
                'long_description' => 'Design stunning email campaigns without coding knowledge. Features a powerful drag-and-drop email builder, responsive templates, A/B testing, personalization tokens, and detailed analytics. Track opens, clicks, and conversions. Includes spam checker, send time optimization, and automated follow-up sequences. Perfect for nurturing leads and customer engagement.',
                'type'             => 'plugin',
                'category_id'      => 6, // sales-marketing
                'price'            => 0.00,
                'status'           => 'approved',
                'downloads_count'  => 3756,
                'average_rating'   => 4.7,
                'featured'         => true,
                'logo'             => 'email-builder-logo.png',
                'screenshots'      => json_encode(['email-1.png', 'email-2.png', 'email-3.png', 'email-4.png']),
                'documentation_url' => 'https://docs.example.com/email-builder',
                'demo_url'         => 'https://demo.example.com/email-builder',
                'repository_url'   => 'https://github.com/example/email-builder',
                'support_email'    => 'support@emailbuilder.com',
                'tags'             => json_encode(['email', 'marketing', 'campaigns', 'templates']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(11),
                'updated_at'       => $now->copy()->subDays(4),
            ],
            [
                'id'               => 11,
                'name'             => 'SMS Marketing Suite',
                'slug'             => 'sms-marketing-suite',
                'description'      => 'Send SMS campaigns and automated text messages to your contacts',
                'long_description' => 'Reach customers instantly with SMS marketing. Send bulk SMS campaigns, automated appointment reminders, order notifications, and promotional messages. Features contact segmentation, message templates, delivery reports, and two-way messaging. Supports 200+ countries with competitive rates. Includes opt-in/opt-out management and compliance tools.',
                'type'             => 'plugin',
                'category_id'      => 6, // sales-marketing
                'price'            => 89.00,
                'status'           => 'approved',
                'downloads_count'  => 967,
                'average_rating'   => 4.3,
                'featured'         => false,
                'logo'             => 'sms-logo.png',
                'screenshots'      => json_encode(['sms-1.png', 'sms-2.png']),
                'documentation_url' => 'https://docs.example.com/sms',
                'demo_url'         => null,
                'repository_url'   => null,
                'support_email'    => 'support@smsextension.com',
                'tags'             => json_encode(['sms', 'marketing', 'messaging', 'notifications']),
                'requirements'     => json_encode(['PHP' => '>=8.0', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(6),
                'updated_at'       => $now->copy()->subDays(18),
            ],

            // Customer Support
            [
                'id'               => 12,
                'name'             => 'Help Desk & Ticketing',
                'slug'             => 'help-desk-ticketing',
                'description'      => 'Complete help desk solution with ticket management and knowledge base',
                'long_description' => 'Transform your CRM into a powerful help desk platform. Manage customer support tickets, create a searchable knowledge base, track SLA compliance, and provide multi-channel support (email, chat, phone). Features include automated ticket routing, canned responses, customer satisfaction surveys, and comprehensive reporting. Includes self-service portal for customers.',
                'type'             => 'plugin',
                'category_id'      => 8, // customer-support
                'price'            => 159.00,
                'status'           => 'approved',
                'downloads_count'  => 1345,
                'average_rating'   => 4.6,
                'featured'         => true,
                'logo'             => 'helpdesk-logo.png',
                'screenshots'      => json_encode(['helpdesk-1.png', 'helpdesk-2.png', 'helpdesk-3.png']),
                'documentation_url' => 'https://docs.example.com/helpdesk',
                'demo_url'         => 'https://demo.example.com/helpdesk',
                'repository_url'   => null,
                'support_email'    => 'support@helpdeskextension.com',
                'tags'             => json_encode(['support', 'tickets', 'helpdesk', 'knowledge-base']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(8),
                'updated_at'       => $now->copy()->subDays(6),
            ],

            // Development Tools
            [
                'id'               => 13,
                'name'             => 'REST API Builder',
                'slug'             => 'rest-api-builder',
                'description'      => 'Create custom REST API endpoints with visual interface',
                'long_description' => 'Extend your CRM with custom API endpoints using a no-code visual builder. Create RESTful APIs for custom integrations, mobile apps, or third-party services. Features automatic documentation generation, authentication options, rate limiting, request validation, and comprehensive logging. Perfect for developers building custom integrations.',
                'type'             => 'plugin',
                'category_id'      => 18, // development-api
                'price'            => 249.00,
                'status'           => 'approved',
                'downloads_count'  => 678,
                'average_rating'   => 4.8,
                'featured'         => false,
                'logo'             => 'api-builder-logo.png',
                'screenshots'      => json_encode(['api-1.png', 'api-2.png', 'api-3.png']),
                'documentation_url' => 'https://docs.example.com/api-builder',
                'demo_url'         => null,
                'repository_url'   => 'https://github.com/example/api-builder',
                'support_email'    => 'support@apibuilder.com',
                'tags'             => json_encode(['api', 'rest', 'development', 'integration']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subMonths(4),
                'updated_at'       => $now->copy()->subDays(14),
            ],

            // Pending/Draft Extensions (for testing different statuses)
            [
                'id'               => 14,
                'name'             => 'WhatsApp Business Integration',
                'slug'             => 'whatsapp-business-integration',
                'description'      => 'Send messages and manage conversations via WhatsApp Business API',
                'long_description' => 'Connect with customers on WhatsApp directly from your CRM. Send notifications, promotional messages, and provide customer support via WhatsApp Business API. Features include chat history, media sharing, template messages, and automated responses. Track conversation metrics and integrate WhatsApp into your existing workflows.',
                'type'             => 'integration',
                'category_id'      => 15, // communication-chat
                'price'            => 69.00,
                'status'           => 'pending',
                'downloads_count'  => 0,
                'average_rating'   => 0,
                'featured'         => false,
                'logo'             => 'whatsapp-logo.png',
                'screenshots'      => json_encode(['whatsapp-1.png']),
                'documentation_url' => null,
                'demo_url'         => null,
                'repository_url'   => null,
                'support_email'    => 'support@whatsappextension.com',
                'tags'             => json_encode(['whatsapp', 'messaging', 'chat', 'communication']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subDays(5),
                'updated_at'       => $now->copy()->subDays(5),
            ],
            [
                'id'               => 15,
                'name'             => 'AI Lead Scoring',
                'slug'             => 'ai-lead-scoring',
                'description'      => 'Automatically score and prioritize leads using machine learning',
                'long_description' => 'Harness the power of AI to identify your best leads. Our machine learning algorithm analyzes historical data to predict which leads are most likely to convert. Features automatic scoring updates, customizable scoring factors, and integration with your sales pipeline. Includes detailed insights into scoring factors and continuous model improvement.',
                'type'             => 'plugin',
                'category_id'      => 3, // productivity
                'price'            => 299.00,
                'status'           => 'draft',
                'downloads_count'  => 0,
                'average_rating'   => 0,
                'featured'         => false,
                'logo'             => 'ai-scoring-logo.png',
                'screenshots'      => json_encode([]),
                'documentation_url' => null,
                'demo_url'         => null,
                'repository_url'   => null,
                'support_email'    => 'support@aiscoringextension.com',
                'tags'             => json_encode(['ai', 'machine-learning', 'lead-scoring', 'sales']),
                'requirements'     => json_encode(['PHP' => '>=8.1', 'Laravel' => '>=10.0']),
                'author_id'        => 1,
                'created_at'       => $now->copy()->subDays(2),
                'updated_at'       => $now->copy()->subDays(2),
            ],
        ];

        DB::table('extensions')->insert($extensions);

        // Create versions for each extension
        $versions = [];
        foreach ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] as $extensionId) {
            // Create multiple versions to show update history
            $versions[] = [
                'extension_id'    => $extensionId,
                'version'         => '1.0.0',
                'changelog'       => 'Initial release with core functionality',
                'file_path'       => "extensions/extension-{$extensionId}/v1.0.0.zip",
                'status'          => 'approved',
                'release_date'    => $now->copy()->subMonths(rand(3, 12)),
                'laravel_version' => '>=10.0',
                'crm_version'     => '>=1.0',
                'php_version'     => '>=8.0',
                'dependencies'    => json_encode([]),
                'downloads_count' => rand(100, 500),
                'file_size'       => rand(500000, 5000000),
                'checksum'        => md5("extension-{$extensionId}-1.0.0"),
                'created_at'      => $now->copy()->subMonths(rand(3, 12)),
                'updated_at'      => $now->copy()->subMonths(rand(3, 12)),
            ];

            $versions[] = [
                'extension_id'    => $extensionId,
                'version'         => '1.1.0',
                'changelog'       => 'Added new features and bug fixes. Improved performance and user experience.',
                'file_path'       => "extensions/extension-{$extensionId}/v1.1.0.zip",
                'status'          => 'approved',
                'release_date'    => $now->copy()->subMonths(rand(1, 3)),
                'laravel_version' => '>=10.0',
                'crm_version'     => '>=1.0',
                'php_version'     => '>=8.0',
                'dependencies'    => json_encode([]),
                'downloads_count' => rand(50, 200),
                'file_size'       => rand(500000, 5000000),
                'checksum'        => md5("extension-{$extensionId}-1.1.0"),
                'created_at'      => $now->copy()->subMonths(rand(1, 3)),
                'updated_at'      => $now->copy()->subMonths(rand(1, 3)),
            ];

            $versions[] = [
                'extension_id'    => $extensionId,
                'version'         => '1.2.0',
                'changelog'       => 'Major update with new features, security improvements, and Laravel 10 compatibility.',
                'file_path'       => "extensions/extension-{$extensionId}/v1.2.0.zip",
                'status'          => 'approved',
                'release_date'    => $now->copy()->subDays(rand(1, 30)),
                'laravel_version' => '>=10.0',
                'crm_version'     => '>=1.0',
                'php_version'     => '>=8.1',
                'dependencies'    => json_encode([]),
                'downloads_count' => rand(10, 100),
                'file_size'       => rand(500000, 5000000),
                'checksum'        => md5("extension-{$extensionId}-1.2.0"),
                'created_at'      => $now->copy()->subDays(rand(1, 30)),
                'updated_at'      => $now->copy()->subDays(rand(1, 30)),
            ];
        }

        // Add a pending version for testing
        $versions[] = [
            'extension_id'    => 1,
            'version'         => '2.0.0',
            'changelog'       => 'Complete rewrite with new architecture. Breaking changes - please review documentation.',
            'file_path'       => 'extensions/extension-1/v2.0.0.zip',
            'status'          => 'pending',
            'release_date'    => null,
            'laravel_version' => '>=10.0',
            'crm_version'     => '>=1.0',
            'php_version'     => '>=8.2',
            'dependencies'    => json_encode(['stripe/stripe-php' => '^10.0']),
            'downloads_count' => 0,
            'file_size'       => 6500000,
            'checksum'        => md5('extension-1-2.0.0'),
            'created_at'      => $now->copy()->subDays(3),
            'updated_at'      => $now->copy()->subDays(3),
        ];

        DB::table('extension_versions')->insert($versions);

        // Create sample reviews for approved extensions
        $reviews = [
            // Stripe Payment Gateway reviews
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Excellent payment integration',
                'review_text'          => 'This extension has completely streamlined our payment processing. The setup was straightforward and the documentation is excellent. Highly recommended for anyone using Stripe.',
                'helpful_count'        => 24,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(45),
                'updated_at'           => $now->copy()->subDays(45),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great extension, minor issues',
                'review_text'          => 'Works well overall. Had some trouble with webhook configuration initially but support helped resolve it quickly. Would be nice to have more customization options for payment forms.',
                'helpful_count'        => 12,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(30),
                'updated_at'           => $now->copy()->subDays(30),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Best payment solution',
                'review_text'          => 'After trying several payment integrations, this is by far the best. Clean code, regular updates, and excellent support. Worth every penny!',
                'helpful_count'        => 18,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(15),
                'updated_at'           => $now->copy()->subDays(15),
            ],

            // Mailchimp Integration reviews
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Perfect for email marketing',
                'review_text'          => 'Syncing contacts with Mailchimp has never been easier. The two-way sync works flawlessly and saves us hours of manual work every week. Great free extension!',
                'helpful_count'        => 35,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(60),
                'updated_at'           => $now->copy()->subDays(60),
            ],
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Works great, needs more features',
                'review_text'          => 'Solid integration that does what it promises. Would love to see support for more custom fields and advanced segmentation options in future updates.',
                'helpful_count'        => 8,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(20),
                'updated_at'           => $now->copy()->subDays(20),
            ],

            // Google Calendar Sync reviews
            [
                'extension_id'         => 3,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Game changer for our team',
                'review_text'          => 'Our sales team lives in Google Calendar and this integration keeps everything in sync perfectly. No more double-booking or missed meetings!',
                'helpful_count'        => 16,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(40),
                'updated_at'           => $now->copy()->subDays(40),
            ],
            [
                'extension_id'         => 3,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Good but could be better',
                'review_text'          => 'The sync works well but occasionally there are delays. Support was helpful in optimizing our setup. Overall a good value for the price.',
                'helpful_count'        => 5,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(25),
                'updated_at'           => $now->copy()->subDays(25),
            ],

            // Slack Notifications reviews
            [
                'extension_id'         => 4,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Must-have for Slack teams',
                'review_text'          => 'Absolutely essential if your team uses Slack. We get instant notifications for new leads and important updates. The slash commands are a nice bonus!',
                'helpful_count'        => 42,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(50),
                'updated_at'           => $now->copy()->subDays(50),
            ],
            [
                'extension_id'         => 4,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Simple and effective',
                'review_text'          => 'Easy to set up and works perfectly. Customization options are great - we can choose exactly what notifications to receive and where.',
                'helpful_count'        => 28,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(10),
                'updated_at'           => $now->copy()->subDays(10),
            ],

            // Modern Dashboard Theme reviews
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Beautiful and functional',
                'review_text'          => 'This theme transformed our CRM! The modern interface is beautiful and the dark mode is perfect for long work sessions. Our team loves it.',
                'helpful_count'        => 21,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(35),
                'updated_at'           => $now->copy()->subDays(35),
            ],
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great theme with minor quirks',
                'review_text'          => 'Love the design and the customization options. Had a couple of CSS conflicts with other extensions but developer helped fix them quickly.',
                'helpful_count'        => 9,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(18),
                'updated_at'           => $now->copy()->subDays(18),
            ],

            // Advanced Reports reviews
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Powerful reporting tool',
                'review_text'          => 'The reporting capabilities are incredible. We can finally create the custom reports our management team needs. The export options are comprehensive too.',
                'helpful_count'        => 31,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(55),
                'updated_at'           => $now->copy()->subDays(55),
            ],
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Worth the investment',
                'review_text'          => 'Pricey but worth every dollar. The scheduled reports alone have saved our team countless hours. The visual builder makes creating complex reports easy.',
                'helpful_count'        => 19,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(12),
                'updated_at'           => $now->copy()->subDays(12),
            ],

            // Task Automation Engine reviews
            [
                'extension_id'         => 8,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Automation made simple',
                'review_text'          => 'The no-code builder is intuitive and powerful. We\'ve automated so many repetitive tasks that were eating up our time. Highly recommend!',
                'helpful_count'        => 27,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(42),
                'updated_at'           => $now->copy()->subDays(42),
            ],

            // Email Campaign Builder reviews
            [
                'extension_id'         => 10,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Amazing free tool',
                'review_text'          => 'Can\'t believe this is free! The email builder is professional-grade and the templates look great. A/B testing feature is very useful.',
                'helpful_count'        => 48,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(65),
                'updated_at'           => $now->copy()->subDays(65),
            ],
            [
                'extension_id'         => 10,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great value',
                'review_text'          => 'Excellent email builder with good analytics. The interface could be more modern but functionality is solid. Great for small to medium campaigns.',
                'helpful_count'        => 14,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(22),
                'updated_at'           => $now->copy()->subDays(22),
            ],

            // Help Desk reviews
            [
                'extension_id'         => 12,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Complete support solution',
                'review_text'          => 'This turned our CRM into a full help desk platform. The ticket management is comprehensive and the knowledge base feature helps reduce support volume.',
                'helpful_count'        => 23,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(38),
                'updated_at'           => $now->copy()->subDays(38),
            ],

            // REST API Builder reviews
            [
                'extension_id'         => 13,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Developer\'s dream',
                'review_text'          => 'As a developer, this extension is gold. Creating custom APIs without writing boilerplate code is fantastic. Documentation generation is a huge time-saver.',
                'helpful_count'        => 15,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(28),
                'updated_at'           => $now->copy()->subDays(28),
            ],
            [
                'extension_id'         => 13,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Powerful but complex',
                'review_text'          => 'Very capable tool but has a learning curve. Once you understand it, you can build anything. Would benefit from more examples and tutorials.',
                'helpful_count'        => 7,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(15),
                'updated_at'           => $now->copy()->subDays(15),
            ],

            // Add a pending review for testing
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 3,
                'title'                => 'Needs improvement',
                'review_text'          => 'The extension works but I encountered several bugs with refund processing. Support has been responsive but waiting for fixes.',
                'helpful_count'        => 0,
                'status'               => 'pending',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(2),
                'updated_at'           => $now->copy()->subDays(2),
            ],
        ];

        DB::table('extension_reviews')->insert($reviews);
    }
}
