<?php

namespace Webkul\Marketplace\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @param  array  $parameters
     * @return void
     */
    public function run($parameters = [])
    {
        DB::table('extension_reviews')->delete();

        $now = Carbon::now();

        $reviews = [
            // Stripe Payment Gateway reviews (Extension ID: 1)
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Excellent payment integration',
                'review_text'          => 'This extension has completely streamlined our payment processing. The setup was straightforward and the documentation is excellent. Highly recommended for anyone using Stripe.',
                'helpful_count'        => 24,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(45),
                'updated_at'           => $now->copy()->subDays(45),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great extension, minor issues',
                'review_text'          => 'Works well overall. Had some trouble with webhook configuration initially but support helped resolve it quickly. Would be nice to have more customization options for payment forms.',
                'helpful_count'        => 12,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(30),
                'updated_at'           => $now->copy()->subDays(30),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Best payment solution',
                'review_text'          => 'After trying several payment integrations, this is by far the best. Clean code, regular updates, and excellent support. Worth every penny!',
                'helpful_count'        => 18,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(15),
                'updated_at'           => $now->copy()->subDays(15),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 3,
                'title'                => 'Needs improvement',
                'review_text'          => 'The extension works but I encountered several bugs with refund processing. Support has been responsive but waiting for fixes.',
                'helpful_count'        => 0,
                'status'               => 'pending',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(2),
                'updated_at'           => $now->copy()->subDays(2),
            ],
            [
                'extension_id'         => 1,
                'user_id'              => 1,
                'rating'               => 2,
                'title'                => 'Disappointing experience',
                'review_text'          => 'Installation broke our site and had to roll back. The requirements were not clearly documented.',
                'helpful_count'        => 3,
                'status'               => 'rejected',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(8),
                'updated_at'           => $now->copy()->subDays(7),
            ],

            // Mailchimp Integration reviews (Extension ID: 2)
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Perfect for email marketing',
                'review_text'          => 'Syncing contacts with Mailchimp has never been easier. The two-way sync works flawlessly and saves us hours of manual work every week. Great free extension!',
                'helpful_count'        => 35,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(60),
                'updated_at'           => $now->copy()->subDays(60),
            ],
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Works great, needs more features',
                'review_text'          => 'Solid integration that does what it promises. Would love to see support for more custom fields and advanced segmentation options in future updates.',
                'helpful_count'        => 8,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(20),
                'updated_at'           => $now->copy()->subDays(20),
            ],
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Essential for our marketing team',
                'review_text'          => 'We use this daily and it has become an essential part of our workflow. The automation features save so much time. Kudos to the developer!',
                'helpful_count'        => 22,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(33),
                'updated_at'           => $now->copy()->subDays(33),
            ],

            // Google Calendar Sync reviews (Extension ID: 3)
            [
                'extension_id'         => 3,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Game changer for our team',
                'review_text'          => 'Our sales team lives in Google Calendar and this integration keeps everything in sync perfectly. No more double-booking or missed meetings!',
                'helpful_count'        => 16,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(40),
                'updated_at'           => $now->copy()->subDays(40),
            ],
            [
                'extension_id'         => 3,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Good but could be better',
                'review_text'          => 'The sync works well but occasionally there are delays. Support was helpful in optimizing our setup. Overall a good value for the price.',
                'helpful_count'        => 5,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(25),
                'updated_at'           => $now->copy()->subDays(25),
            ],
            [
                'extension_id'         => 3,
                'user_id'              => 1,
                'rating'               => 3,
                'title'                => 'Works but has issues',
                'review_text'          => 'Calendar sync is useful but I experienced some duplicated events. Hoping for improvements in the next version.',
                'helpful_count'        => 2,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(12),
                'updated_at'           => $now->copy()->subDays(12),
            ],

            // Slack Notifications reviews (Extension ID: 4)
            [
                'extension_id'         => 4,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Must-have for Slack teams',
                'review_text'          => 'Absolutely essential if your team uses Slack. We get instant notifications for new leads and important updates. The slash commands are a nice bonus!',
                'helpful_count'        => 42,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(50),
                'updated_at'           => $now->copy()->subDays(50),
            ],
            [
                'extension_id'         => 4,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Simple and effective',
                'review_text'          => 'Easy to set up and works perfectly. Customization options are great - we can choose exactly what notifications to receive and where.',
                'helpful_count'        => 28,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(10),
                'updated_at'           => $now->copy()->subDays(10),
            ],
            [
                'extension_id'         => 4,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Very useful integration',
                'review_text'          => 'Great for keeping the team informed. Would love to see more formatting options for messages and better thread organization.',
                'helpful_count'        => 11,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(28),
                'updated_at'           => $now->copy()->subDays(28),
            ],

            // Modern Dashboard Theme reviews (Extension ID: 5)
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Beautiful and functional',
                'review_text'          => 'This theme transformed our CRM! The modern interface is beautiful and the dark mode is perfect for long work sessions. Our team loves it.',
                'helpful_count'        => 21,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(35),
                'updated_at'           => $now->copy()->subDays(35),
            ],
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great theme with minor quirks',
                'review_text'          => 'Love the design and the customization options. Had a couple of CSS conflicts with other extensions but developer helped fix them quickly.',
                'helpful_count'        => 9,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(18),
                'updated_at'           => $now->copy()->subDays(18),
            ],
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Best theme available',
                'review_text'          => 'Tried several themes and this one stands out. The attention to detail is impressive and performance is excellent. Worth the investment.',
                'helpful_count'        => 14,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(6),
                'updated_at'           => $now->copy()->subDays(6),
            ],

            // Classic Enterprise Theme reviews (Extension ID: 6)
            [
                'extension_id'         => 6,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Professional and secure',
                'review_text'          => 'Perfect for our enterprise environment. The security features and compliance indicators are exactly what we needed. Clean, professional look.',
                'helpful_count'        => 7,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(22),
                'updated_at'           => $now->copy()->subDays(22),
            ],
            [
                'extension_id'         => 6,
                'user_id'              => 1,
                'rating'               => 3,
                'title'                => 'Good but dated design',
                'review_text'          => 'Functional and meets our security requirements but the design feels a bit outdated compared to modern alternatives. Does the job though.',
                'helpful_count'        => 4,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(14),
                'updated_at'           => $now->copy()->subDays(14),
            ],

            // Advanced Reports & Analytics reviews (Extension ID: 7)
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Powerful reporting tool',
                'review_text'          => 'The reporting capabilities are incredible. We can finally create the custom reports our management team needs. The export options are comprehensive too.',
                'helpful_count'        => 31,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(55),
                'updated_at'           => $now->copy()->subDays(55),
            ],
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Worth the investment',
                'review_text'          => 'Pricey but worth every dollar. The scheduled reports alone have saved our team countless hours. The visual builder makes creating complex reports easy.',
                'helpful_count'        => 19,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(12),
                'updated_at'           => $now->copy()->subDays(12),
            ],
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Comprehensive analytics',
                'review_text'          => 'Excellent reporting features with lots of customization. Learning curve is a bit steep but documentation helps. Would recommend for data-driven teams.',
                'helpful_count'        => 13,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(27),
                'updated_at'           => $now->copy()->subDays(27),
            ],

            // Task Automation Engine reviews (Extension ID: 8)
            [
                'extension_id'         => 8,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Automation made simple',
                'review_text'          => 'The no-code builder is intuitive and powerful. We\'ve automated so many repetitive tasks that were eating up our time. Highly recommend!',
                'helpful_count'        => 27,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(42),
                'updated_at'           => $now->copy()->subDays(42),
            ],
            [
                'extension_id'         => 8,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great productivity booster',
                'review_text'          => 'Really useful for automating workflows. Some advanced features could be more intuitive but overall very satisfied with the results.',
                'helpful_count'        => 9,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(19),
                'updated_at'           => $now->copy()->subDays(19),
            ],

            // Document Management Pro reviews (Extension ID: 9)
            [
                'extension_id'         => 9,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Solid document solution',
                'review_text'          => 'Good document management with versioning and templates. The OCR feature works well. A few minor bugs but support is responsive.',
                'helpful_count'        => 10,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(31),
                'updated_at'           => $now->copy()->subDays(31),
            ],
            [
                'extension_id'         => 9,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Everything we needed',
                'review_text'          => 'Perfect for managing customer documents. The e-signature integration is fantastic and the branded portal looks professional.',
                'helpful_count'        => 15,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(17),
                'updated_at'           => $now->copy()->subDays(17),
            ],

            // Email Campaign Builder reviews (Extension ID: 10)
            [
                'extension_id'         => 10,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Amazing free tool',
                'review_text'          => 'Can\'t believe this is free! The email builder is professional-grade and the templates look great. A/B testing feature is very useful.',
                'helpful_count'        => 48,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(65),
                'updated_at'           => $now->copy()->subDays(65),
            ],
            [
                'extension_id'         => 10,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great value',
                'review_text'          => 'Excellent email builder with good analytics. The interface could be more modern but functionality is solid. Great for small to medium campaigns.',
                'helpful_count'        => 14,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(22),
                'updated_at'           => $now->copy()->subDays(22),
            ],
            [
                'extension_id'         => 10,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Best free extension',
                'review_text'          => 'We switched from a paid service to this and haven\'t looked back. The drag-and-drop builder is easy to use and results are professional.',
                'helpful_count'        => 33,
                'status'               => 'approved',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(38),
                'updated_at'           => $now->copy()->subDays(38),
            ],

            // SMS Marketing Suite reviews (Extension ID: 11)
            [
                'extension_id'         => 11,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Effective SMS marketing',
                'review_text'          => 'Good SMS capabilities with worldwide coverage. Delivery reports are accurate and the two-way messaging works well. Price is reasonable.',
                'helpful_count'        => 6,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(26),
                'updated_at'           => $now->copy()->subDays(26),
            ],
            [
                'extension_id'         => 11,
                'user_id'              => 1,
                'rating'               => 3,
                'title'                => 'Works but needs polish',
                'review_text'          => 'Does what it says but the interface could be more user-friendly. Message templates are helpful but limited customization options.',
                'helpful_count'        => 2,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(11),
                'updated_at'           => $now->copy()->subDays(11),
            ],

            // Help Desk & Ticketing reviews (Extension ID: 12)
            [
                'extension_id'         => 12,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Complete support solution',
                'review_text'          => 'This turned our CRM into a full help desk platform. The ticket management is comprehensive and the knowledge base feature helps reduce support volume.',
                'helpful_count'        => 23,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(38),
                'updated_at'           => $now->copy()->subDays(38),
            ],
            [
                'extension_id'         => 12,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Great help desk features',
                'review_text'          => 'Excellent ticketing system with good SLA tracking. The customer portal is a nice touch. Would like to see more integrations with chat platforms.',
                'helpful_count'        => 12,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(21),
                'updated_at'           => $now->copy()->subDays(21),
            ],

            // REST API Builder reviews (Extension ID: 13)
            [
                'extension_id'         => 13,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Developer\'s dream',
                'review_text'          => 'As a developer, this extension is gold. Creating custom APIs without writing boilerplate code is fantastic. Documentation generation is a huge time-saver.',
                'helpful_count'        => 15,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(28),
                'updated_at'           => $now->copy()->subDays(28),
            ],
            [
                'extension_id'         => 13,
                'user_id'              => 1,
                'rating'               => 4,
                'title'                => 'Powerful but complex',
                'review_text'          => 'Very capable tool but has a learning curve. Once you understand it, you can build anything. Would benefit from more examples and tutorials.',
                'helpful_count'        => 7,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(15),
                'updated_at'           => $now->copy()->subDays(15),
            ],
            [
                'extension_id'         => 13,
                'user_id'              => 1,
                'rating'               => 5,
                'title'                => 'Best API builder',
                'review_text'          => 'Incredible tool for building custom integrations. The rate limiting and authentication features are production-ready. Highly recommend for any developer.',
                'helpful_count'        => 11,
                'status'               => 'approved',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(5),
                'updated_at'           => $now->copy()->subDays(5),
            ],

            // Additional varied reviews for testing different scenarios
            [
                'extension_id'         => 2,
                'user_id'              => 1,
                'rating'               => 1,
                'title'                => 'Completely broken',
                'review_text'          => 'This extension caused our entire CRM to crash. Had to restore from backup. Very disappointed.',
                'helpful_count'        => 5,
                'status'               => 'flagged',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(3),
                'updated_at'           => $now->copy()->subDays(3),
            ],
            [
                'extension_id'         => 5,
                'user_id'              => 1,
                'rating'               => 2,
                'title'                => 'Not worth the price',
                'review_text'          => 'Theme looks nice in screenshots but has performance issues. Page load times increased significantly after installation.',
                'helpful_count'        => 1,
                'status'               => 'pending',
                'is_verified_purchase' => true,
                'created_at'           => $now->copy()->subDays(1),
                'updated_at'           => $now->copy()->subDays(1),
            ],
            [
                'extension_id'         => 7,
                'user_id'              => 1,
                'rating'               => 1,
                'title'                => 'Spam review test',
                'review_text'          => 'CHECK OUT MY WEBSITE FOR BETTER DEALS!!!',
                'helpful_count'        => 0,
                'status'               => 'rejected',
                'is_verified_purchase' => false,
                'created_at'           => $now->copy()->subDays(10),
                'updated_at'           => $now->copy()->subDays(9),
            ],
        ];

        DB::table('extension_reviews')->insert($reviews);
    }
}
